homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 5
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Copenhagen
  customize: !include_dir_merge_named customize

  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 10.4.1.0/24
        - 127.0.0.1

zone:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  icon: mdi:worker

# Frontend and iOS app
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

mobile_app:
ios:

# Enables configuration UI
config:

system_health:

http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_cert_path
  ssl_key: !secret ssl_key_path
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - all_lights
      - binary_sensor
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.last_boot
      - sensor.new_commits
      - script.get_latest_config
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.exchange_rate_1_btc
      - sensor.ha_uptime

logbook:
  exclude:
    entities:
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.time
      - sensor.date
      - sensor.since_last_boot
      - sensor.exchange_rate_1_btc
      - sensor.ha_uptime

# Track the sun
sun:

# Text to speech
tts:
  platform: google_translate

media_player:
  - platform: samsungtv
    host: 10.4.1.101
    port: 8001
    mac: !secret tv_mac

  - platform: apple_tv
    host: !secret apple_tv_host
    login_id: !secret apple_tv_login_id
    credentials: !secret apple_tv_credentials
    start_off: true

# hue:
#   bridges:
#     - allow_hue_groups: false

tado:
  username: !secret tado_username
  password: !secret tado_password

climate:
  platform: tado

notify:
  - platform: ios

ifttt:
  key: !secret ifttt_key

device_tracker:
  - platform: tado
    username: !secret tado_username
    password: !secret tado_password
    home_id: !secret tado_home_id

homekit:
  filter:
    include_entities:
      - light.entre
      - media_player.samsung_tv_remote

remote:
  - platform: harmony
    name: Harmony Hub

vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_ip
    token: !secret vacuum_token

recorder:
  purge_keep_days: 2
  purge_interval: 1

speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload
  server_id: 8751

fan:
  - platform: xiaomi_miio
    host: !secret fan_ip
    token: !secret vacuum_token

pi_hole:

# Includes
automation: !include automations.yaml
group: !include groups.yaml
switch: !include switch.yaml
sensor: !include_dir_merge_list sensor
script: !include script.yaml
