homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 5
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Copenhagen
  customize: !include_dir_merge_named customize

# Frontend and iOS app
frontend:
ios:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  trusted_networks:
    - 10.4.1.0/24
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 3
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

history:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.new_commits
      - script.get_latest_config
      - sensor.pihole_ads_blocked_today

logbook:
  exclude:
    entities:
      - sensor.pihole_ads_blocked_today
      - sensor.time
      - sensor.date
      - sensor.since_last_boot

# Track the sun
sun:

# Text to speech
tts:
  platform: google
  language: 'da'

media_player:
  - platform: samsungtv
    host: 10.4.1.101
    port: 8001
    mac: !secret tv_mac

tado:
  username: !secret tado_username
  password: !secret tado_password

climate:
  platform: tado

notify:
  - platform: ios

ifttt:
  key: !secret ifttt_key

panel_iframe:
  laundry_room:
    title: 'Laundry Room'
    icon: mdi:washing-machine
    url: !secret laundry_url
  pi_hole:
    title: 'Pi-hole'
    icon: mdi:chart-pie
    url: 'http://10.4.1.140/admin/'

device_tracker:
    - platform: tado
      username: !secret tado_username
      password: !secret tado_password
      home_id: !secret tado_home_id

  # - platform: nmap_tracker
  #   hosts: 10.4.1.100-149
  #   track_new_devices: no
  #   home_interval: 20
  #   exclude:
  #     - 10.4.1.140
  #     - 10.4.1.102

# Includes
automation: !include_dir_list automation
group: !include groups.yaml
switch: !include switch.yaml
sensor: !include_dir_merge_list sensor
script: !include_dir_named script
shell_command: !include_dir_named shell_command
