homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 5
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Copenhagen
  customize: !include_dir_merge_named customize

zone:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  icon: mdi:worker

# Frontend and iOS app
frontend:
  themes: !include_dir_merge_named themes

ios:

# Enables configuration UI
config:

http:
  base_url: !secret base_url
  api_password: !secret http_password
  ssl_certificate: !secret ssl_cert_path
  ssl_key: !secret ssl_key_path
  trusted_networks:
    - 10.4.1.0/24
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

history:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.last_boot
      - sensor.new_commits
      - script.get_latest_config
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.since_last_boot_templated
      - sensor.exchange_rate_1_btc

logbook:
  exclude:
    entities:
      - sensor.pihole_ads_blocked_today
      - sensor.time
      - sensor.date
      - sensor.since_last_boot
      - sensor.exchange_rate_1_btc

# Track the sun
sun:

# Text to speech
tts:
  platform: google
  language: 'da'

media_player:
  - platform: samsungtv
    host: 10.4.1.101
    port: 8001
    mac: !secret tv_mac

  - platform: apple_tv
    host: !secret apple_tv_host
    login_id: !secret apple_tv_login_id
    credentials: !secret apple_tv_credentials

tado:
  username: !secret tado_username
  password: !secret tado_password

climate:
  platform: tado

notify:
  - platform: ios

ifttt:
  key: !secret ifttt_key

device_tracker:
    - platform: tado
      username: !secret tado_username
      password: !secret tado_password
      home_id: !secret tado_home_id

# Includes
automation old: !include_dir_list automation
automation: !include automations.yaml
group: !include groups.yaml
switch: !include switch.yaml
sensor: !include_dir_merge_list sensor
script: !include_dir_named script
shell_command: !include_dir_named shell_command
