default_view:
  icon: mdi:home
  entities:
    - group.all_devices
    - group.all_lights
    - group.all_vacuum_cleaners
    - group.main_stuff
    - climate.living_zone
    - sun.sun
    - sensor.yr_symbol
    - sensor.yr_temperature
    - sensor.us_air_pollution_level
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.exchange_rate_1_btc

media:
  name: Media
  view: yes
  icon: mdi:play-circle-outline
  entities:
    - group.sonos
    - group.tv

automation:
  name: Automation
  view: yes
  icon: mdi:settings
  entities:
    - group.all_automations

SystemView:
  name: System
  view: yes
  icon: mdi:server
  entities:
    - group.system
    - sensor.ssl_certificate_expiry
    - sensor.current_version
    - sensor.uptime

System:
  name: System
  entities:
    - sensor.processor_use
    - sensor.disk_use_percent
    - sensor.memory_free
    - sensor.network_in_eth0
    - sensor.network_out_eth0
    - sensor.last_boot
    - sensor.fogh_homeassistant_config_state

Sonos:
  - media_player.kokken
  - media_player.sovevaerelse
  - media_player.spisestue
  - media_player.stue
  - media_player.badevaerelse

Main_Stuff:
  name: Main Stuff
  entities:
    - switch.playstation4
    - media_player.samsung_tv_remote
    - vacuum.xiaomi_vacuum_cleaner
    # - switch.desk_lamp

TV:
  - media_player.apple_tv
