default_view:
  view: yes
  icon: mdi:home
  entities:
    - group.all_devices
    - group.all_lights
    - group.main_stuff
    - climate.living_zone
    - sun.sun
    - sensor.yr_symbol
    - sensor.yr_temperature
    - sensor.us_air_pollution_level
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.pihole_ads_blocked_today
    - sensor.exchange_rate_1_btc

media:
  name: Media
  view: yes
  icon: mdi:play-circle-outline
  entities:
    - group.sonos
    - group.tv

automation:
  name: Automation
  view: yes
  icon: mdi:settings
  entities:
    - group.all_automations

SystemView:
  name: System
  view: yes
  icon: mdi:server
  entities:
    - group.system
    - script.deploy_config
    - sensor.ssl_certificate_expiry
    - sensor.current_version
    - sensor.uptime

System:
  name: System
  entities:
    - sensor.cpu_use
    - sensor.disk_use_
    - sensor.ram_free
    - sensor.received_eth0
    - sensor.sent_eth0
    - sensor.last_boot
    - sensor.foghhomeassistantconfig_state

Sonos:
  - media_player.kkken
  - media_player.sovevrelse
  - media_player.spisestue
  - media_player.stue

Main_Stuff:
  name: Main Stuff
  entities:
    - switch.playstation4
    - media_player.samsung_tv_remote
    - switch.desk_lamp

TV:
  - media_player.apple_tv
