- platform: command_line
  switches:
    playstation4:
      command_on: 'ps4-waker'
      command_off: 'ps4-waker standby'
      command_state: 'nmap -p 9295 10.4.1.116 | grep -w -Eo "open" '
      value_template: '{{ value == "open" }}'
      friendly_name: "Playstation 4"

- platform: tplink
  host: 10.4.1.137
  name: 'Bedroom TV'

- platform: wake_on_lan
  name: iMac
  mac_address: !secret mac_mac_address
