alias: "Deploy config"
sequence:
  - condition: state
    entity_id: sensor.foghhomeassistantconfig_state
    state: 'passed'
  - service: shell_command.update_config
  - delay: 00:00:30
  - service: homeassistant.restart
