- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: last_boot

- platform: yr
  monitored_conditions:
    - symbol
    - temperature

- platform: cert_expiry
  host: !secret base_url

- platform: travisci
  api_key: !secret github_token
  scan_interval: 60
  monitored_conditions:
    - state
  repository:
    - homeassistant-config

- platform: bitcoin
  display_options:
    - exchangerate

- platform: version

- platform: uptime

- platform: airvisual
  api_key: !secret airvisual_key
