alias: 'Away mode'
trigger:
  platform: state
  entity_id: sensor.living_zone_tado_mode
  from: 'HOME'
  to: 'AWAY'

condition:
  - condition: state
    entity_id: media_player.samsung_tv_remote
    state: 'on'

action:
  - service: media_player.turn_off
    entity_id: media_player.samsung_tv_remote
  - service: notify.notify
    data:
      message: 'You forgot to turn off the TV. It has been automatically turned off'
